package com.kantamori.simpleping;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

/**
 * Generated by Kanta Mori on 3/12/2017.
 */

public class HistoryOpenHelper extends SQLiteOpenHelper {
    public Context context;
    public static final String TAG = "HistoryOpenHelper";
    public static final int DB_VERSION = 1;
    static final String DB = "history_sqlite.db";
    static final String CREATE_TABLE = "create table mytable (host text primary key, state integer, date integer);";
    static final String DROP_TABLE = "drop table mytable";

    public HistoryOpenHelper (final Context context) {
        super(context, DB, null, DB_VERSION);
        this.context = context;
    }

    @Override
    public void onCreate(final SQLiteDatabase db) {
        //Log.d(TAG, "onCreate: version : " + db.getVersion());
        db.execSQL(CREATE_TABLE);
    }

    @Override
    public void onUpgrade(final SQLiteDatabase db, final int oldVersion, final  int newVersion) {
        db.execSQL(DROP_TABLE);
        onCreate(db);
    }
}
