package com.kantamori.simpleping;

import android.os.Bundle;
import android.preference.PreferenceFragment;

/**
 * Generated by Kanta Mori on 3/12/2017.
 */

public class SettingsFragment extends PreferenceFragment {
    //public static final String FRAGMENT_NAME = SettingsFragment.class.getName();

    @Override
    public void onCreate (Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addPreferencesFromResource(R.xml.preferences);
    }
}
